version: "3.7"
services:
  skku-autocomplete-batch:
    image: sinkyoungdeok/skku-autocomplete-batch
  skku-autocomplete:
    depends_on:
      - skku-redis
    image: sinkyoungdeok/skku-autocomplete
    ports:
      - "8090:8090"
    restart: always
  skku-api-1:
    depends_on:
      - skku-db
    image: sinkyoungdeok/skku-api
    ports:
      - "8081:8081"
    environment:
      - USE_PROFILE=prod1
    env_file:
      - .env
    restart: always
  skku-api-2:
    depends_on:
      - skku-db
    image: sinkyoungdeok/skku-api
    ports:
      - "8082:8082"
    environment:
      - USE_PROFILE=prod2
    env_file:
      - .env
    restart: always
  skku-db:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=skku
      - MYSQL_ROOT_PASSWORD=skku-be
      - MYSQL_USER=skku-user
      - MYSQL_PASSWORD=skku-pw
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
  skku-redis:
    image: redis:6.0.2
    command: redis-server /usr/local/etc/redis/redis.conf --port 6379
    ports:
      - 6379:6379
    platform: linux/amd64
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/users.acl:/usr/local/etc/redis/users.acl:rw

  es-singlenode:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: es-singlenode
    environment:
      - xpack.security.enabled=false
      - node.name=single-node
      - cluster.name=kdsin
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    container_name: docker-kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://es-singlenode:9200"]'
    ports:
      - 5601:5601
    expose:
      - 5601
    volumes:
      - ./kibana-config.yml:/usr/share/kibana/config/kibana.yml
    restart: always
